base_url = "https://cluzeau.pro"
title = "Cluzeau"

compile_sass = true
build_search_index = false

theme = "even"

taxonomies = [
    # You can enable/disable RSS
    # { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# top syntax themes
# highlight_theme = "1337"
# highlight_theme = "ayu-dark"
# highlight_theme = "ayu-mirage"
# highlight_theme = "dracula"
# highlight_theme = "gruvbox-dark"
# highlight_theme = "kronuz"
# highlight_theme = "material-dark"
# highlight_theme = "monokai"
highlight_theme = "nyx-bold"
# highlight_theme = "one-dark"
# highlight_theme = "OneHalfDark"
# highlight_theme = "solarized-dark"
# highlight_theme = "two-dark"


# highlight_theme = "agola-dark"
# highlight_theme = "ascetic-white"
# highlight_theme = "axar"
# highlight_theme = "ayu-light"
# highlight_theme = "base16-atelierdune-light"
# highlight_theme = "base16-ocean-dark" # default
# highlight_theme = "base16-ocean-light"
# highlight_theme = "bbedit"
# highlight_theme = "boron"
# highlight_theme = "charcoal"
# highlight_theme = "cheerfully-light"
# highlight_theme = "classic-modified"
# highlight_theme = "demain"
# highlight_theme = "dimmed-fluid"
# highlight_theme = "gray-matter-dark"
# highlight_theme = "green"
# highlight_theme = "gruvbox-light"
# highlight_theme = "idle"
# highlight_theme = "inspired-github"
# highlight_theme = "ir-white"
# highlight_theme = "material-light"
# highlight_theme = "nord"
# highlight_theme = "OneHalfLight"
# highlight_theme = "railsbase16-green-screen-dark"
# highlight_theme = "solarized-light"
# highlight_theme = "subway-madrid"
# highlight_theme = "subway-moscow"
# highlight_theme = "Tomorrow"
# highlight_theme = "visual-studio-dark"
# highlight_theme = "zenburn"


[extra]
even_menu = [
    { url = "$BASE_URL", name = "Home" },
    # { url = "$BASE_URL/categories", name = "Categories" },
    { url = "$BASE_URL/tags", name = "Tags" },
    # { url = "$BASE_URL/about", name = "About" },
    { url = "https://resume.cluzeau.pro", name = "Resume" },
    { url = "https://github.com/aurelien-clu", name = "Github" },
    { url = "https://www.linkedin.com/in/aurelien-clu/", name = "LinkedIn" },
]
even_title = "Cluzeau"

descriptions = [
    { content = "A blog with concise & opinionated posts about development, data science, business & management." },
    # { content = "Feel free to reach out :)"},
]
top_tags = [
    # { content = "tags/tldr"},
    # { content = "tags/rust"},
    # { content = "tags/event-sourcing"},
    # { content = "tags/python"},
]
