base_url = "https://cluzeau.pro"
title = "Cluzeau"

compile_sass = true
build_search_index = false

theme = "even"

taxonomies = [
    # You can enable/disable RSS
    # { name = "categories", feed = true },
    { name = "tags", feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
even_menu = [
    { url = "$BASE_URL", name = "Home" },
    # { url = "$BASE_URL/categories", name = "Categories" },
    { url = "$BASE_URL/tags", name = "Tags" },
    # { url = "$BASE_URL/about", name = "About" },
    { url = "https://resume.cluzeau.pro", name = "Resume" },
    { url = "https://github.com/aurelien-clu", name = "Github" },
    { url = "https://www.linkedin.com/in/aurelien-clu/", name = "LinkedIn" },
]
even_title = "Cluzeau"
